Hemoglobin (g/dL):
  normal_range: [13.5, 17.5]
  risk:
    Low: "Anemia"
    High: "Polycythemia"

Glucose (mg/dL):
  normal_range: [70, 99]
  risk:
    High: "Diabetes risk"

HbA1c (%):
  normal_range: [4.0, 5.6]
  risk:
    High: "Diabetes"

ALT (U/L):
  normal_range: [7, 56]
  risk:
    High: "Liver stress"

Platelets (10^3/Î¼L):
  normal_range: [150, 450]
  risk:
    Low: "Bleeding risk"
